-- =============================================================================
-- 01_base_tables_and_data.sql
-- Supply Chain Knowledge Graph — Base Tables & Synthetic Data (Full Scale)
-- Database: SCS | Schema: INVENTORY
-- Deterministic seed: 20260917
-- =============================================================================

USE ROLE SUPPLYCHAIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCS;
USE SCHEMA INVENTORY;

-- =============================================================================
-- SECTION 1: REFERENCE DIMENSIONS
-- =============================================================================

-- DIM_DATE: 2022-01-01 through 2026-12-31 (1,826 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_DATE (
    DATE_KEY        DATE        NOT NULL PRIMARY KEY,
    YEAR            INT         NOT NULL,
    QUARTER         INT         NOT NULL,
    MONTH           INT         NOT NULL,
    MONTH_NAME      VARCHAR(10) NOT NULL,
    WEEK_OF_YEAR    INT         NOT NULL,
    DAY_OF_WEEK     INT         NOT NULL,
    DAY_NAME        VARCHAR(10) NOT NULL,
    IS_WEEKEND      BOOLEAN     NOT NULL,
    FISCAL_YEAR     INT         NOT NULL,
    FISCAL_QUARTER  INT         NOT NULL
) COMMENT = 'Calendar dimension from 2022-01-01 to 2026-12-31';

INSERT INTO SCS.INVENTORY.DIM_DATE
SELECT
    DT,
    YEAR(DT),
    QUARTER(DT),
    MONTH(DT),
    MONTHNAME(DT),
    WEEKOFYEAR(DT),
    DAYOFWEEK(DT),
    DAYNAME(DT),
    DAYOFWEEK(DT) IN (0, 6),
    CASE WHEN MONTH(DT) >= 7 THEN YEAR(DT) + 1 ELSE YEAR(DT) END,
    CASE WHEN MONTH(DT) >= 7 THEN QUARTER(DT) - 2 ELSE QUARTER(DT) + 2 END
FROM (
    SELECT DATEADD(DAY, SEQ4(), '2022-01-01'::DATE) AS DT
    FROM TABLE(GENERATOR(ROWCOUNT => 1827))
)
WHERE DT <= '2026-12-31';

-- DIM_GEO_REGION (6 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_GEO_REGION (
    REGION_ID   INT         NOT NULL PRIMARY KEY,
    REGION_NAME VARCHAR(50) NOT NULL
) COMMENT = 'Geographic regions';

INSERT INTO SCS.INVENTORY.DIM_GEO_REGION
SELECT ROW_NUMBER() OVER (ORDER BY 1), R.VALUE::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    'North America','Europe','East Asia','Southeast Asia','South Asia','Latin America'
))) R;

-- DIM_GEO_COUNTRY (24 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_GEO_COUNTRY (
    COUNTRY_ID   INT         NOT NULL PRIMARY KEY,
    COUNTRY_NAME VARCHAR(50) NOT NULL,
    COUNTRY_CODE VARCHAR(3)  NOT NULL,
    REGION_ID    INT         NOT NULL REFERENCES SCS.INVENTORY.DIM_GEO_REGION(REGION_ID)
) COMMENT = 'Countries mapped to regions';

INSERT INTO SCS.INVENTORY.DIM_GEO_COUNTRY
SELECT ROW_NUMBER() OVER (ORDER BY R.VALUE[2]::INT, R.VALUE[0]::VARCHAR),
       R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR, R.VALUE[2]::INT
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('United States','US',1), ARRAY_CONSTRUCT('Canada','CA',1),
    ARRAY_CONSTRUCT('Mexico','MX',1), ARRAY_CONSTRUCT('Brazil','BR',6),
    ARRAY_CONSTRUCT('Germany','DE',2), ARRAY_CONSTRUCT('France','FR',2),
    ARRAY_CONSTRUCT('United Kingdom','GB',2), ARRAY_CONSTRUCT('Netherlands','NL',2),
    ARRAY_CONSTRUCT('Italy','IT',2), ARRAY_CONSTRUCT('Poland','PL',2),
    ARRAY_CONSTRUCT('China','CN',3), ARRAY_CONSTRUCT('Japan','JP',3),
    ARRAY_CONSTRUCT('South Korea','KR',3), ARRAY_CONSTRUCT('Taiwan','TW',3),
    ARRAY_CONSTRUCT('Malaysia','MY',4), ARRAY_CONSTRUCT('Vietnam','VN',4),
    ARRAY_CONSTRUCT('Thailand','TH',4), ARRAY_CONSTRUCT('Singapore','SG',4),
    ARRAY_CONSTRUCT('Philippines','PH',4), ARRAY_CONSTRUCT('Indonesia','ID',4),
    ARRAY_CONSTRUCT('India','IN',5), ARRAY_CONSTRUCT('Argentina','AR',6),
    ARRAY_CONSTRUCT('Colombia','CO',6), ARRAY_CONSTRUCT('Chile','CL',6)
))) R;

-- DIM_COMMODITY (12 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_COMMODITY (
    COMMODITY_ID   INT         NOT NULL PRIMARY KEY,
    COMMODITY_NAME VARCHAR(50) NOT NULL
) COMMENT = 'Top-level commodity classification';

INSERT INTO SCS.INVENTORY.DIM_COMMODITY
SELECT ROW_NUMBER() OVER (ORDER BY 1), C.VALUE::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    'Semiconductors','Passive Components','Connectors','PCB & Substrates',
    'Mechanical Parts','Packaging Materials','Optical Components','Power Supplies',
    'Sensors','Cable & Wire','Raw Materials','Chemicals'
))) C;

-- DIM_SUB_COMMODITY (36 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_SUB_COMMODITY (
    SUB_COMMODITY_ID   INT         NOT NULL PRIMARY KEY,
    SUB_COMMODITY_NAME VARCHAR(80) NOT NULL,
    COMMODITY_ID       INT         NOT NULL REFERENCES SCS.INVENTORY.DIM_COMMODITY(COMMODITY_ID)
) COMMENT = 'Sub-commodity classification';

INSERT INTO SCS.INVENTORY.DIM_SUB_COMMODITY
SELECT ROW_NUMBER() OVER (ORDER BY R.VALUE[1]::INT, R.VALUE[0]::VARCHAR),
       R.VALUE[0]::VARCHAR, R.VALUE[1]::INT
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('MCU & Microprocessors',1), ARRAY_CONSTRUCT('Memory ICs',1), ARRAY_CONSTRUCT('Analog ICs',1),
    ARRAY_CONSTRUCT('Resistors',2), ARRAY_CONSTRUCT('Capacitors',2), ARRAY_CONSTRUCT('Inductors',2),
    ARRAY_CONSTRUCT('Board-to-Board',3), ARRAY_CONSTRUCT('Wire-to-Board',3), ARRAY_CONSTRUCT('RF Connectors',3),
    ARRAY_CONSTRUCT('Rigid PCB',4), ARRAY_CONSTRUCT('Flex PCB',4), ARRAY_CONSTRUCT('Ceramic Substrates',4),
    ARRAY_CONSTRUCT('Enclosures',5), ARRAY_CONSTRUCT('Heat Sinks',5), ARRAY_CONSTRUCT('Fasteners',5),
    ARRAY_CONSTRUCT('Boxes & Cartons',6), ARRAY_CONSTRUCT('ESD Bags',6), ARRAY_CONSTRUCT('Foam Inserts',6),
    ARRAY_CONSTRUCT('LEDs',7), ARRAY_CONSTRUCT('Laser Diodes',7), ARRAY_CONSTRUCT('Photodetectors',7),
    ARRAY_CONSTRUCT('AC-DC Converters',8), ARRAY_CONSTRUCT('DC-DC Converters',8), ARRAY_CONSTRUCT('Battery Packs',8),
    ARRAY_CONSTRUCT('Temperature Sensors',9), ARRAY_CONSTRUCT('Pressure Sensors',9), ARRAY_CONSTRUCT('Accelerometers',9),
    ARRAY_CONSTRUCT('Power Cable',10), ARRAY_CONSTRUCT('Signal Cable',10), ARRAY_CONSTRUCT('Fiber Optic',10),
    ARRAY_CONSTRUCT('Aluminum',11), ARRAY_CONSTRUCT('Steel',11), ARRAY_CONSTRUCT('Copper',11),
    ARRAY_CONSTRUCT('Solder Paste',12), ARRAY_CONSTRUCT('Flux',12), ARRAY_CONSTRUCT('Conformal Coating',12)
))) R;

-- DIM_CURRENCY (12 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_CURRENCY (
    CURRENCY_CODE VARCHAR(3) NOT NULL PRIMARY KEY,
    CURRENCY_NAME VARCHAR(50) NOT NULL,
    TO_USD_RATE   DECIMAL(10,4) NOT NULL COMMENT 'Approximate fixed rate for demo'
) COMMENT = 'Currency reference with approximate USD exchange rates';

INSERT INTO SCS.INVENTORY.DIM_CURRENCY
SELECT R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR, R.VALUE[2]::DECIMAL(10,4)
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('USD','US Dollar',1.0000),
    ARRAY_CONSTRUCT('EUR','Euro',1.0800),
    ARRAY_CONSTRUCT('GBP','British Pound',1.2700),
    ARRAY_CONSTRUCT('JPY','Japanese Yen',0.0067),
    ARRAY_CONSTRUCT('CNY','Chinese Yuan',0.1380),
    ARRAY_CONSTRUCT('KRW','South Korean Won',0.0007),
    ARRAY_CONSTRUCT('TWD','Taiwan Dollar',0.0310),
    ARRAY_CONSTRUCT('MYR','Malaysian Ringgit',0.2200),
    ARRAY_CONSTRUCT('THB','Thai Baht',0.0280),
    ARRAY_CONSTRUCT('INR','Indian Rupee',0.0120),
    ARRAY_CONSTRUCT('MXN','Mexican Peso',0.0580),
    ARRAY_CONSTRUCT('BRL','Brazilian Real',0.2000)
))) R;

-- DIM_UOM (12 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_UOM (
    UOM_CODE VARCHAR(5) NOT NULL PRIMARY KEY,
    UOM_NAME VARCHAR(30) NOT NULL
) COMMENT = 'Units of measure';

INSERT INTO SCS.INVENTORY.DIM_UOM
SELECT R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('EA','Each'), ARRAY_CONSTRUCT('KG','Kilogram'),
    ARRAY_CONSTRUCT('M','Meter'), ARRAY_CONSTRUCT('L','Liter'),
    ARRAY_CONSTRUCT('FT','Foot'), ARRAY_CONSTRUCT('LB','Pound'),
    ARRAY_CONSTRUCT('PC','Piece'), ARRAY_CONSTRUCT('SET','Set'),
    ARRAY_CONSTRUCT('ROL','Roll'), ARRAY_CONSTRUCT('BOX','Box'),
    ARRAY_CONSTRUCT('PAL','Pallet'), ARRAY_CONSTRUCT('SHT','Sheet')
))) R;

-- DIM_INCOTERM (11 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_INCOTERM (
    INCOTERM_CODE VARCHAR(3) NOT NULL PRIMARY KEY,
    INCOTERM_NAME VARCHAR(50) NOT NULL
) COMMENT = 'Incoterms 2020';

INSERT INTO SCS.INVENTORY.DIM_INCOTERM
SELECT R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('EXW','Ex Works'), ARRAY_CONSTRUCT('FCA','Free Carrier'),
    ARRAY_CONSTRUCT('FAS','Free Alongside Ship'), ARRAY_CONSTRUCT('FOB','Free on Board'),
    ARRAY_CONSTRUCT('CFR','Cost and Freight'), ARRAY_CONSTRUCT('CIF','Cost Insurance Freight'),
    ARRAY_CONSTRUCT('CPT','Carriage Paid To'), ARRAY_CONSTRUCT('CIP','Carriage Insurance Paid'),
    ARRAY_CONSTRUCT('DAP','Delivered at Place'), ARRAY_CONSTRUCT('DPU','Delivered at Place Unloaded'),
    ARRAY_CONSTRUCT('DDP','Delivered Duty Paid')
))) R;

-- DIM_PORT (40 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_PORT (
    PORT_ID    INT         NOT NULL PRIMARY KEY,
    PORT_NAME  VARCHAR(80) NOT NULL,
    PORT_CODE  VARCHAR(10) NOT NULL,
    COUNTRY_ID INT         NOT NULL,
    PORT_TYPE  VARCHAR(10) NOT NULL COMMENT 'SEA, AIR, or BOTH'
) COMMENT = 'Major ports and airports for logistics';

INSERT INTO SCS.INVENTORY.DIM_PORT
SELECT ROW_NUMBER() OVER (ORDER BY R.VALUE[3]::INT, R.VALUE[0]::VARCHAR),
       R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR, R.VALUE[2]::INT, R.VALUE[3]::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('Port of Los Angeles','USLAX',1,'SEA'),
    ARRAY_CONSTRUCT('Port of Long Beach','USLGB',1,'SEA'),
    ARRAY_CONSTRUCT('Port of Savannah','USSAV',1,'SEA'),
    ARRAY_CONSTRUCT('Port of Houston','USHOU',1,'SEA'),
    ARRAY_CONSTRUCT('JFK Airport','USJFK',1,'AIR'),
    ARRAY_CONSTRUCT('Chicago OHare','USORD',1,'AIR'),
    ARRAY_CONSTRUCT('Port of Vancouver','CAVAN',2,'SEA'),
    ARRAY_CONSTRUCT('Port of Manzanillo','MXMAN',3,'SEA'),
    ARRAY_CONSTRUCT('Port of Lazaro Cardenas','MXLZC',3,'SEA'),
    ARRAY_CONSTRUCT('Guadalajara Airport','MXGDL',3,'AIR'),
    ARRAY_CONSTRUCT('Port of Santos','BRSTS',4,'SEA'),
    ARRAY_CONSTRUCT('Port of Hamburg','DEHAM',5,'SEA'),
    ARRAY_CONSTRUCT('Frankfurt Airport','DEFRA',5,'AIR'),
    ARRAY_CONSTRUCT('Port of Rotterdam','NLRTM',8,'SEA'),
    ARRAY_CONSTRUCT('Port of Le Havre','FRLEH',6,'SEA'),
    ARRAY_CONSTRUCT('Port of Felixstowe','GBFXT',7,'SEA'),
    ARRAY_CONSTRUCT('Heathrow Airport','GBLHR',7,'AIR'),
    ARRAY_CONSTRUCT('Port of Genoa','ITGOA',9,'SEA'),
    ARRAY_CONSTRUCT('Port of Gdansk','PLGDN',10,'SEA'),
    ARRAY_CONSTRUCT('Port of Shanghai','CNSHA',11,'SEA'),
    ARRAY_CONSTRUCT('Port of Shenzhen','CNSZX',11,'SEA'),
    ARRAY_CONSTRUCT('Port of Ningbo','CNNBO',11,'SEA'),
    ARRAY_CONSTRUCT('Shanghai Pudong Airport','CNPVG',11,'AIR'),
    ARRAY_CONSTRUCT('Shenzhen Airport','CNSZX_A',11,'AIR'),
    ARRAY_CONSTRUCT('Port of Tokyo','JPTYO',12,'SEA'),
    ARRAY_CONSTRUCT('Narita Airport','JPNRT',12,'AIR'),
    ARRAY_CONSTRUCT('Port of Busan','KRPUS',13,'SEA'),
    ARRAY_CONSTRUCT('Port of Kaohsiung','TWKHH',14,'SEA'),
    ARRAY_CONSTRUCT('Taoyuan Airport','TWTPE',14,'AIR'),
    ARRAY_CONSTRUCT('Port of Penang','MYPEN',15,'SEA'),
    ARRAY_CONSTRUCT('Port Klang','MYPKG',15,'SEA'),
    ARRAY_CONSTRUCT('Port of Ho Chi Minh','VNSGN',16,'SEA'),
    ARRAY_CONSTRUCT('Port of Laem Chabang','THLCH',17,'SEA'),
    ARRAY_CONSTRUCT('Port of Singapore','SGSIN',18,'BOTH'),
    ARRAY_CONSTRUCT('Port of Manila','PHMNL',19,'SEA'),
    ARRAY_CONSTRUCT('Port of Jakarta','IDJKT',20,'SEA'),
    ARRAY_CONSTRUCT('Port of Mumbai','INBOM',21,'SEA'),
    ARRAY_CONSTRUCT('Port of Chennai','INMAA',21,'SEA'),
    ARRAY_CONSTRUCT('Port of Buenos Aires','ARBUE',22,'SEA'),
    ARRAY_CONSTRUCT('Port of Valparaiso','CLVAP',24,'SEA')
))) R;

-- =============================================================================
-- SECTION 2: MASTER DATA — SUPPLIERS
-- =============================================================================

CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_SUPPLIER (
    SUPPLIER_ID        INT          NOT NULL PRIMARY KEY,
    SUPPLIER_NAME      VARCHAR(200) NOT NULL,
    SUPPLIER_CODE      VARCHAR(20)  NOT NULL,
    COUNTRY_ID         INT          NOT NULL,
    COMMODITY_ID       INT          NOT NULL,
    RELIABILITY_RATING DECIMAL(3,2) NOT NULL COMMENT '0.00-1.00 scale',
    IS_PROBLEM         BOOLEAN      DEFAULT FALSE COMMENT 'Flagged problem supplier for demo scenarios',
    ACTIVE             BOOLEAN      DEFAULT TRUE,
    IS_SYNTHETIC       BOOLEAN      DEFAULT TRUE
) COMMENT = 'Supplier master — 500 suppliers across commodities and countries';

-- Generate 500 suppliers deterministically
INSERT INTO SCS.INVENTORY.DIM_SUPPLIER
WITH SUPPLIER_PREFIXES AS (
    SELECT R.VALUE::VARCHAR AS PREFIX, R.INDEX AS IDX FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
        'NEXORA','BLUEFORGE','PENTAWAVE','VERTEX','SOLARIS','QUANTUM','APEX','ORION',
        'TITAN','ZENITH','NOVA','PRISM','ATLAS','ECHO','CIPHER','HELIX','FLUX',
        'IONIC','VORTEX','STELLAR','CREST','LUNAR','COBALT','AETHER','MATRIX',
        'SYNTH','PULSE','DRIFT','OMEGA','SIGMA','DELTA','GAMMA','ZETA','KAPPA',
        'THETA','ALPHA','BETA','EPSILON','LAMBDA','IOTA','TORUS','NEXUS','PYRO',
        'CRYO','FERRO','AERO','HYDRO','ELECTRO','MAGNETO','PHOTON'
    ))) R
),
SUPPLIER_SUFFIXES AS (
    SELECT R.VALUE::VARCHAR AS SUFFIX, R.INDEX AS IDX FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
        'SEMICONDUCTORS','COMPONENTS','MATERIALS','ELECTRONICS','TECHNOLOGIES',
        'PRECISION','SYSTEMS','SOLUTIONS','INDUSTRIES','MANUFACTURING'
    ))) R
),
SUPPLIER_BASE AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY P.IDX, S.IDX) AS RN,
        P.PREFIX || ' ' || S.SUFFIX AS SNAME,
        P.PREFIX,
        S.SUFFIX
    FROM SUPPLIER_PREFIXES P
    CROSS JOIN SUPPLIER_SUFFIXES S
)
SELECT
    RN AS SUPPLIER_ID,
    SNAME AS SUPPLIER_NAME,
    'SUP-' || LPAD(RN::VARCHAR, 5, '0') AS SUPPLIER_CODE,
    MOD(ABS(HASH(RN, 20260917)), 24) + 1 AS COUNTRY_ID,
    MOD(ABS(HASH(RN, 20260918)), 12) + 1 AS COMMODITY_ID,
    ROUND(0.60 + (MOD(ABS(HASH(RN, 20260919)), 40) / 100.0), 2) AS RELIABILITY_RATING,
    SNAME IN ('NEXORA SEMICONDUCTORS','BLUEFORGE COMPONENTS','PENTAWAVE MATERIALS') AS IS_PROBLEM,
    TRUE AS ACTIVE,
    TRUE AS IS_SYNTHETIC
FROM SUPPLIER_BASE
WHERE RN <= 500;

-- DIM_SUPPLIER_SITE (1,200 rows — ~2.4 sites per supplier)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_SUPPLIER_SITE (
    SITE_ID       INT          NOT NULL PRIMARY KEY,
    SUPPLIER_ID   INT          NOT NULL REFERENCES SCS.INVENTORY.DIM_SUPPLIER(SUPPLIER_ID),
    SITE_NAME     VARCHAR(200) NOT NULL,
    CITY          VARCHAR(100) NOT NULL,
    COUNTRY_ID    INT          NOT NULL,
    LEAD_TIME_DAYS INT         NOT NULL COMMENT 'Average lead time in calendar days',
    IS_PRIMARY    BOOLEAN      DEFAULT FALSE,
    ACTIVE        BOOLEAN      DEFAULT TRUE
) COMMENT = 'Supplier manufacturing and shipping sites';

INSERT INTO SCS.INVENTORY.DIM_SUPPLIER_SITE
WITH CITIES AS (
    SELECT R.VALUE[0]::VARCHAR AS CITY, R.VALUE[1]::INT AS CID, R.INDEX AS IDX
    FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
        ARRAY_CONSTRUCT('Austin',1),ARRAY_CONSTRUCT('San Jose',1),ARRAY_CONSTRUCT('Detroit',1),
        ARRAY_CONSTRUCT('Toronto',2),ARRAY_CONSTRUCT('Monterrey',3),ARRAY_CONSTRUCT('Guadalajara',3),
        ARRAY_CONSTRUCT('Sao Paulo',4),ARRAY_CONSTRUCT('Munich',5),ARRAY_CONSTRUCT('Stuttgart',5),
        ARRAY_CONSTRUCT('Paris',6),ARRAY_CONSTRUCT('London',7),ARRAY_CONSTRUCT('Amsterdam',8),
        ARRAY_CONSTRUCT('Milan',9),ARRAY_CONSTRUCT('Warsaw',10),
        ARRAY_CONSTRUCT('Shanghai',11),ARRAY_CONSTRUCT('Shenzhen',11),ARRAY_CONSTRUCT('Beijing',11),
        ARRAY_CONSTRUCT('Suzhou',11),ARRAY_CONSTRUCT('Dongguan',11),
        ARRAY_CONSTRUCT('Tokyo',12),ARRAY_CONSTRUCT('Osaka',12),
        ARRAY_CONSTRUCT('Seoul',13),ARRAY_CONSTRUCT('Hsinchu',14),ARRAY_CONSTRUCT('Taichung',14),
        ARRAY_CONSTRUCT('Penang',15),ARRAY_CONSTRUCT('Kuala Lumpur',15),
        ARRAY_CONSTRUCT('Ho Chi Minh City',16),ARRAY_CONSTRUCT('Hanoi',16),
        ARRAY_CONSTRUCT('Bangkok',17),ARRAY_CONSTRUCT('Singapore',18),
        ARRAY_CONSTRUCT('Manila',19),ARRAY_CONSTRUCT('Jakarta',20),
        ARRAY_CONSTRUCT('Bangalore',21),ARRAY_CONSTRUCT('Chennai',21),ARRAY_CONSTRUCT('Pune',21),
        ARRAY_CONSTRUCT('Buenos Aires',22),ARRAY_CONSTRUCT('Bogota',23),ARRAY_CONSTRUCT('Santiago',24)
    ))) R
),
SITE_GEN AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY S.SUPPLIER_ID, C.IDX) AS SITE_ID,
        S.SUPPLIER_ID,
        S.SUPPLIER_NAME || ' - ' || C.CITY AS SITE_NAME,
        C.CITY,
        C.CID AS COUNTRY_ID,
        14 + MOD(ABS(HASH(S.SUPPLIER_ID, C.IDX, 20260917)), 60) AS LEAD_TIME_DAYS,
        ROW_NUMBER() OVER (PARTITION BY S.SUPPLIER_ID ORDER BY C.IDX) AS SITE_RANK
    FROM SCS.INVENTORY.DIM_SUPPLIER S
    CROSS JOIN CITIES C
    WHERE MOD(ABS(HASH(S.SUPPLIER_ID, C.IDX, 20260920)), 100) < 
          CASE WHEN S.SUPPLIER_ID <= 3 THEN 15 ELSE 7 END
)
SELECT
    SITE_ID,
    SUPPLIER_ID,
    SITE_NAME,
    CITY,
    COUNTRY_ID,
    LEAD_TIME_DAYS,
    SITE_RANK = 1 AS IS_PRIMARY,
    TRUE AS ACTIVE
FROM SITE_GEN
WHERE SITE_ID <= 1200;

-- =============================================================================
-- SECTION 3: MASTER DATA — PARTS, PRODUCTS, BOMS
-- =============================================================================

-- DIM_MANUFACTURER (200 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_MANUFACTURER (
    MANUFACTURER_ID   INT          NOT NULL PRIMARY KEY,
    MANUFACTURER_NAME VARCHAR(200) NOT NULL,
    COUNTRY_ID        INT          NOT NULL
) COMMENT = 'Component manufacturers';

INSERT INTO SCS.INVENTORY.DIM_MANUFACTURER
SELECT
    SEQ8() + 1 AS MANUFACTURER_ID,
    ARRAY_CONSTRUCT('TechCore','MicroEdge','NanoBridge','SiliconWave','ChipLogic',
        'CircuitPeak','DigiForge','PowerLink','SenseCore','OptoMax',
        'ResistoPro','CapaciTech','InductoStar','ConnectWave','BoardMaster',
        'MechaParts','PackRight','LaserPoint','VoltEdge','SensorX')[MOD(SEQ8(),20)]::VARCHAR
        || ' ' ||
        ARRAY_CONSTRUCT('Corp','Inc','Ltd','GmbH','SA','Co','AG','BV','KK','Pte')[MOD(DIV0(SEQ8(),20),10)]::VARCHAR
        AS MANUFACTURER_NAME,
    MOD(ABS(HASH(SEQ8(), 20260917)), 24) + 1 AS COUNTRY_ID
FROM TABLE(GENERATOR(ROWCOUNT => 200));

-- DIM_PART (30,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_PART (
    PART_ID          INT           NOT NULL PRIMARY KEY,
    PART_NUMBER      VARCHAR(30)   NOT NULL,
    PART_NAME        VARCHAR(200)  NOT NULL,
    COMMODITY_ID     INT           NOT NULL,
    SUB_COMMODITY_ID INT           NOT NULL,
    UOM_CODE         VARCHAR(5)    DEFAULT 'EA',
    UNIT_COST_USD    DECIMAL(10,2) NOT NULL COMMENT 'Standard cost in USD',
    WEIGHT_KG        DECIMAL(8,3),
    LIFECYCLE_STATUS VARCHAR(20)   DEFAULT 'ACTIVE' COMMENT 'ACTIVE, EOL, OBSOLETE, NRND',
    IS_SYNTHETIC     BOOLEAN       DEFAULT TRUE
) COMMENT = 'Part master — 30,000 parts across all commodities';

INSERT INTO SCS.INVENTORY.DIM_PART
WITH PART_GEN AS (
    SELECT
        SEQ8() + 1 AS RN,
        MOD(ABS(HASH(SEQ8(), 20260917)), 12) + 1 AS COMM_ID
    FROM TABLE(GENERATOR(ROWCOUNT => 30000))
)
SELECT
    RN AS PART_ID,
    'P-' || LPAD(RN::VARCHAR, 6, '0') AS PART_NUMBER,
    ARRAY_CONSTRUCT('MCU','DRAM','OpAmp','Resistor','Capacitor','Inductor',
        'Connector','PCB','Enclosure','Heatsink','LED','Converter',
        'TempSensor','Cable','Aluminum','SolderPaste')[MOD(RN, 16)]::VARCHAR
        || '-' || LPAD(RN::VARCHAR, 5, '0') AS PART_NAME,
    COMM_ID AS COMMODITY_ID,
    (COMM_ID - 1) * 3 + MOD(ABS(HASH(RN, 20260918)), 3) + 1 AS SUB_COMMODITY_ID,
    'EA' AS UOM_CODE,
    ROUND(0.01 + MOD(ABS(HASH(RN, 20260919)), 50000) / 100.0, 2) AS UNIT_COST_USD,
    ROUND(0.001 + MOD(ABS(HASH(RN, 20260920)), 10000) / 1000.0, 3) AS WEIGHT_KG,
    CASE MOD(ABS(HASH(RN, 20260921)), 100)
        WHEN 0 THEN 'OBSOLETE'
        WHEN 1 THEN 'EOL'
        WHEN 2 THEN 'NRND'
        ELSE 'ACTIVE'
    END AS LIFECYCLE_STATUS,
    TRUE AS IS_SYNTHETIC
FROM PART_GEN;

-- DIM_PRODUCT_FAMILY (60 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_PRODUCT_FAMILY (
    PRODUCT_FAMILY_ID   INT         NOT NULL PRIMARY KEY,
    PRODUCT_FAMILY_NAME VARCHAR(100) NOT NULL
) COMMENT = 'Finished product families';

INSERT INTO SCS.INVENTORY.DIM_PRODUCT_FAMILY
SELECT SEQ8() + 1,
    ARRAY_CONSTRUCT('SmartSense','PowerDrive','ConnectX','VisionPro','AudioMax',
        'ThermoGuard','NavCore','EcoCharge','UltraLink','FlexBoard',
        'LightPulse','MotionCtrl','SafeNet','DataStream','CloudEdge',
        'RoboArm','BioScan','SolarInv','WindCtrl','AquaMon',
        'AutoPilot','GridSync','MedPulse','AirPure','SmartLock',
        'CamView','DroneNav','EVCharge','HeatPump','SoundBar',
        'LEDPanel','MotorDrv','SensFusion','RFModule','PowerBank',
        'DisplayHD','KeyPad','TouchCtrl','VoiceBox','LaserCut',
        'WeldCtrl','PumpDrive','ValveCtrl','FlowMeter','LevelSense',
        'PressGuard','TempLog','HumidCtrl','VibMon','LoadCell',
        'TorqueSns','SpeedCtrl','PosSense','ProxDet','ColorSns',
        'GasDet','PHMeter','TurbSense','GenCtrl','InvBoard')[SEQ8()]::VARCHAR
FROM TABLE(GENERATOR(ROWCOUNT => 60));

-- DIM_PRODUCT (500 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_PRODUCT (
    PRODUCT_ID        INT           NOT NULL PRIMARY KEY,
    PRODUCT_NAME      VARCHAR(200)  NOT NULL,
    PRODUCT_FAMILY_ID INT           NOT NULL,
    UNIT_PRICE_USD    DECIMAL(10,2) NOT NULL,
    IS_SYNTHETIC      BOOLEAN       DEFAULT TRUE
) COMMENT = 'Finished products — 500 SKUs';

INSERT INTO SCS.INVENTORY.DIM_PRODUCT
SELECT
    SEQ8() + 1 AS PRODUCT_ID,
    'PROD-' || LPAD((SEQ8()+1)::VARCHAR, 4, '0') AS PRODUCT_NAME,
    MOD(SEQ8(), 60) + 1 AS PRODUCT_FAMILY_ID,
    ROUND(50.00 + MOD(ABS(HASH(SEQ8(), 20260917)), 200000) / 100.0, 2) AS UNIT_PRICE_USD,
    TRUE
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- BOM_HEADER (1,500 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.BOM_HEADER (
    BOM_ID     INT         NOT NULL PRIMARY KEY,
    PRODUCT_ID INT         NOT NULL,
    BOM_VERSION VARCHAR(10) NOT NULL DEFAULT 'A',
    EFFECTIVE_DATE DATE    NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE'
) COMMENT = 'Bill of Materials headers — one per product revision';

INSERT INTO SCS.INVENTORY.BOM_HEADER
SELECT
    SEQ8() + 1 AS BOM_ID,
    MOD(SEQ8(), 500) + 1 AS PRODUCT_ID,
    CHR(65 + MOD(DIV0(SEQ8(), 500), 3)) AS BOM_VERSION,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260917)), 1000), '2023-01-01') AS EFFECTIVE_DATE,
    'ACTIVE'
FROM TABLE(GENERATOR(ROWCOUNT => 1500));

-- BOM_LINE (15,000 rows — ~10 components per BOM)
CREATE OR REPLACE TABLE SCS.INVENTORY.BOM_LINE (
    BOM_LINE_ID    INT           NOT NULL PRIMARY KEY,
    BOM_ID         INT           NOT NULL,
    PART_ID        INT           NOT NULL,
    QUANTITY_PER   DECIMAL(10,4) NOT NULL,
    FIND_NUMBER    INT           NOT NULL COMMENT 'Position on the BOM'
) COMMENT = 'BOM line items — components per assembly';

INSERT INTO SCS.INVENTORY.BOM_LINE
SELECT
    SEQ8() + 1 AS BOM_LINE_ID,
    DIV0(SEQ8(), 10) + 1 AS BOM_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 30000) + 1 AS PART_ID,
    ROUND(1 + MOD(ABS(HASH(SEQ8(), 20260918)), 20), 0) AS QUANTITY_PER,
    MOD(SEQ8(), 10) + 1 AS FIND_NUMBER
FROM TABLE(GENERATOR(ROWCOUNT => 15000));

-- =============================================================================
-- SECTION 4: NETWORK — PLANTS, WAREHOUSES, CUSTOMERS, CARRIERS, LANES
-- =============================================================================

-- DIM_PLANT (12 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_PLANT (
    PLANT_ID   INT          NOT NULL PRIMARY KEY,
    PLANT_CODE VARCHAR(10)  NOT NULL,
    PLANT_NAME VARCHAR(100) NOT NULL,
    CITY       VARCHAR(100) NOT NULL,
    COUNTRY_ID INT          NOT NULL
) COMMENT = 'Manufacturing plants for Asterion Devices';

INSERT INTO SCS.INVENTORY.DIM_PLANT
SELECT R.INDEX + 1, R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR, R.VALUE[2]::VARCHAR, R.VALUE[3]::INT
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('PLT-US01','Asterion Austin Plant','Austin',1),
    ARRAY_CONSTRUCT('PLT-US02','Asterion San Jose Plant','San Jose',1),
    ARRAY_CONSTRUCT('PLT-US03','Asterion Detroit Plant','Detroit',1),
    ARRAY_CONSTRUCT('PLT-MX01','Asterion Guadalajara Plant','Guadalajara',3),
    ARRAY_CONSTRUCT('PLT-MX02','Asterion Monterrey Plant','Monterrey',3),
    ARRAY_CONSTRUCT('PLT-DE01','Asterion Munich Plant','Munich',5),
    ARRAY_CONSTRUCT('PLT-CN01','Asterion Shanghai Plant','Shanghai',11),
    ARRAY_CONSTRUCT('PLT-CN02','Asterion Shenzhen Plant','Shenzhen',11),
    ARRAY_CONSTRUCT('PLT-JP01','Asterion Tokyo Plant','Tokyo',12),
    ARRAY_CONSTRUCT('PLT-MY01','Asterion Penang Plant','Penang',15),
    ARRAY_CONSTRUCT('PLT-IN01','Asterion Bangalore Plant','Bangalore',21),
    ARRAY_CONSTRUCT('PLT-BR01','Asterion Sao Paulo Plant','Sao Paulo',4)
))) R;

-- DIM_WAREHOUSE (25 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_WAREHOUSE (
    WAREHOUSE_ID   INT          NOT NULL PRIMARY KEY,
    WAREHOUSE_CODE VARCHAR(10)  NOT NULL,
    WAREHOUSE_NAME VARCHAR(100) NOT NULL,
    PLANT_ID       INT,
    CITY           VARCHAR(100) NOT NULL,
    COUNTRY_ID     INT          NOT NULL,
    CAPACITY_UNITS INT          NOT NULL
) COMMENT = 'Warehouses — plant-attached and distribution centers';

INSERT INTO SCS.INVENTORY.DIM_WAREHOUSE
SELECT
    SEQ8() + 1 AS WAREHOUSE_ID,
    'WH-' || LPAD((SEQ8()+1)::VARCHAR, 3, '0') AS WAREHOUSE_CODE,
    'Warehouse ' || (SEQ8()+1)::VARCHAR AS WAREHOUSE_NAME,
    CASE WHEN SEQ8() < 12 THEN SEQ8() + 1 ELSE NULL END AS PLANT_ID,
    COALESCE(P.CITY, 
        ARRAY_CONSTRUCT('Dallas','Atlanta','Chicago','Memphis','Los Angeles',
            'Rotterdam','Singapore','Hong Kong','Tokyo','Dubai',
            'Mumbai','Sao Paulo','Mexico City')[MOD(SEQ8()-12, 13)]::VARCHAR
    ) AS CITY,
    COALESCE(P.COUNTRY_ID,
        ARRAY_CONSTRUCT(1,1,1,1,1,8,18,11,12,21,21,4,3)[MOD(SEQ8()-12, 13)]::INT
    ) AS COUNTRY_ID,
    50000 + MOD(ABS(HASH(SEQ8(), 20260917)), 200000) AS CAPACITY_UNITS
FROM TABLE(GENERATOR(ROWCOUNT => 25)) G
LEFT JOIN SCS.INVENTORY.DIM_PLANT P ON P.PLANT_ID = SEQ8() + 1 AND SEQ8() < 12;

-- DIM_CUSTOMER (80 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_CUSTOMER (
    CUSTOMER_ID   INT          NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_CODE VARCHAR(20)  NOT NULL,
    COUNTRY_ID    INT          NOT NULL,
    CUSTOMER_TIER VARCHAR(10)  NOT NULL COMMENT 'PLATINUM, GOLD, SILVER, BRONZE',
    IS_SYNTHETIC  BOOLEAN      DEFAULT TRUE
) COMMENT = 'Customer master — 80 customers';

INSERT INTO SCS.INVENTORY.DIM_CUSTOMER
WITH CUST_NAMES AS (
    SELECT R.VALUE::VARCHAR AS CNAME, R.INDEX AS IDX FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
        'HELIOS MOBILITY','AQUILA ENERGY','NOVA HOME SYSTEMS','TITAN AEROSPACE','PHOENIX AUTOMOTIVE',
        'AURORA MEDICAL','MERIDIAN DEFENSE','CATALYST ROBOTICS','PINNACLE TELECOM','HORIZON RAIL',
        'SYNERGY MARINE','GRANITE CONSTRUCTION','SAPPHIRE LOGISTICS','EMERALD RETAIL','DIAMOND MINING',
        'CRIMSON PHARMA','INDIGO TEXTILES','AMBER AGRICULTURE','JADE ELECTRONICS','RUBY POWER'
    ))) R
)
SELECT
    SEQ8() + 1 AS CUSTOMER_ID,
    CASE WHEN SEQ8() < 20 THEN C.CNAME
         ELSE 'Customer-' || LPAD((SEQ8()+1)::VARCHAR, 4, '0')
    END AS CUSTOMER_NAME,
    'CUST-' || LPAD((SEQ8()+1)::VARCHAR, 4, '0') AS CUSTOMER_CODE,
    MOD(ABS(HASH(SEQ8(), 20260917)), 24) + 1 AS COUNTRY_ID,
    CASE MOD(ABS(HASH(SEQ8(), 20260918)), 4)
        WHEN 0 THEN 'PLATINUM'
        WHEN 1 THEN 'GOLD'
        WHEN 2 THEN 'SILVER'
        ELSE 'BRONZE'
    END AS CUSTOMER_TIER,
    TRUE
FROM TABLE(GENERATOR(ROWCOUNT => 80))
LEFT JOIN CUST_NAMES C ON C.IDX = SEQ8();

-- DIM_CARRIER (20 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_CARRIER (
    CARRIER_ID   INT          NOT NULL PRIMARY KEY,
    CARRIER_NAME VARCHAR(100) NOT NULL,
    CARRIER_MODE VARCHAR(20)  NOT NULL COMMENT 'OCEAN, AIR, TRUCK, RAIL, MULTIMODAL'
) COMMENT = 'Logistics carriers';

INSERT INTO SCS.INVENTORY.DIM_CARRIER
SELECT R.INDEX + 1, R.VALUE[0]::VARCHAR, R.VALUE[1]::VARCHAR
FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
    ARRAY_CONSTRUCT('Pacific Shipping Co','OCEAN'),
    ARRAY_CONSTRUCT('Atlantic Lines','OCEAN'),
    ARRAY_CONSTRUCT('Global Ocean Freight','OCEAN'),
    ARRAY_CONSTRUCT('Asia Express Shipping','OCEAN'),
    ARRAY_CONSTRUCT('EuroSea Transport','OCEAN'),
    ARRAY_CONSTRUCT('SkyFreight Global','AIR'),
    ARRAY_CONSTRUCT('AirCargo Express','AIR'),
    ARRAY_CONSTRUCT('JetLogistics','AIR'),
    ARRAY_CONSTRUCT('Pacific Air Cargo','AIR'),
    ARRAY_CONSTRUCT('TransAir Services','AIR'),
    ARRAY_CONSTRUCT('Highway Logistics','TRUCK'),
    ARRAY_CONSTRUCT('Continental Trucking','TRUCK'),
    ARRAY_CONSTRUCT('FastLane Transport','TRUCK'),
    ARRAY_CONSTRUCT('CrossBorder Freight','TRUCK'),
    ARRAY_CONSTRUCT('Metro Delivery Co','TRUCK'),
    ARRAY_CONSTRUCT('RailConnect','RAIL'),
    ARRAY_CONSTRUCT('TransRail Cargo','RAIL'),
    ARRAY_CONSTRUCT('InterRail Logistics','RAIL'),
    ARRAY_CONSTRUCT('OmniLogistics','MULTIMODAL'),
    ARRAY_CONSTRUCT('IntegFreight Solutions','MULTIMODAL')
))) R;

-- DIM_LANE (500 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_LANE (
    LANE_ID          INT         NOT NULL PRIMARY KEY,
    ORIGIN_PORT_ID   INT         NOT NULL,
    DEST_PORT_ID     INT         NOT NULL,
    TRANSPORT_MODE   VARCHAR(20) NOT NULL,
    TRANSIT_DAYS_AVG INT         NOT NULL,
    IS_PROBLEM_LANE  BOOLEAN     DEFAULT FALSE
) COMMENT = 'Shipping lanes between ports';

INSERT INTO SCS.INVENTORY.DIM_LANE
WITH LANE_GEN AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY O.PORT_ID, D.PORT_ID) AS RN,
        O.PORT_ID AS ORIGIN_PORT_ID,
        D.PORT_ID AS DEST_PORT_ID,
        CASE
            WHEN O.PORT_TYPE = 'AIR' OR D.PORT_TYPE = 'AIR' THEN 'AIR'
            ELSE 'OCEAN'
        END AS TRANSPORT_MODE,
        CASE
            WHEN O.PORT_TYPE = 'AIR' OR D.PORT_TYPE = 'AIR' THEN 2 + MOD(ABS(HASH(O.PORT_ID, D.PORT_ID)), 5)
            ELSE 14 + MOD(ABS(HASH(O.PORT_ID, D.PORT_ID)), 30)
        END AS TRANSIT_DAYS_AVG
    FROM SCS.INVENTORY.DIM_PORT O
    CROSS JOIN SCS.INVENTORY.DIM_PORT D
    WHERE O.PORT_ID != D.PORT_ID
      AND MOD(ABS(HASH(O.PORT_ID, D.PORT_ID, 20260917)), 100) < 35
)
SELECT
    RN AS LANE_ID,
    ORIGIN_PORT_ID,
    DEST_PORT_ID,
    TRANSPORT_MODE,
    TRANSIT_DAYS_AVG,
    -- Mark Shenzhen-to-Guadalajara ocean lane as problem
    (ORIGIN_PORT_ID IN (SELECT PORT_ID FROM SCS.INVENTORY.DIM_PORT WHERE PORT_CODE = 'CNSZX')
     AND DEST_PORT_ID IN (SELECT PORT_ID FROM SCS.INVENTORY.DIM_PORT WHERE PORT_CODE = 'MXGDL'))
    AS IS_PROBLEM_LANE
FROM LANE_GEN
WHERE RN <= 500;

-- DIM_CONTRACT (300 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.DIM_CONTRACT (
    CONTRACT_ID    INT          NOT NULL PRIMARY KEY,
    SUPPLIER_ID    INT          NOT NULL,
    CONTRACT_CODE  VARCHAR(20)  NOT NULL,
    START_DATE     DATE         NOT NULL,
    END_DATE       DATE         NOT NULL,
    CURRENCY_CODE  VARCHAR(3)   DEFAULT 'USD',
    INCOTERM_CODE  VARCHAR(3),
    STATUS         VARCHAR(20)  DEFAULT 'ACTIVE'
) COMMENT = 'Supplier contracts';

INSERT INTO SCS.INVENTORY.DIM_CONTRACT
SELECT
    SEQ8() + 1 AS CONTRACT_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1 AS SUPPLIER_ID,
    'CTR-' || LPAD((SEQ8()+1)::VARCHAR, 5, '0') AS CONTRACT_CODE,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260918)), 730), '2023-01-01') AS START_DATE,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260918)), 730) + 365 + MOD(ABS(HASH(SEQ8(), 20260919)), 365), '2023-01-01') AS END_DATE,
    ARRAY_CONSTRUCT('USD','EUR','CNY','JPY','KRW')[MOD(ABS(HASH(SEQ8(), 20260920)), 5)]::VARCHAR AS CURRENCY_CODE,
    ARRAY_CONSTRUCT('FOB','CIF','DDP','EXW','DAP')[MOD(ABS(HASH(SEQ8(), 20260921)), 5)]::VARCHAR AS INCOTERM_CODE,
    'ACTIVE'
FROM TABLE(GENERATOR(ROWCOUNT => 300));

-- SUPPLIER_PART_APPROVAL (links suppliers to parts they can supply)
CREATE OR REPLACE TABLE SCS.INVENTORY.SUPPLIER_PART_APPROVAL (
    APPROVAL_ID   INT     NOT NULL PRIMARY KEY,
    SUPPLIER_ID   INT     NOT NULL,
    SITE_ID       INT     NOT NULL,
    PART_ID       INT     NOT NULL,
    APPROVAL_DATE DATE    NOT NULL,
    STATUS        VARCHAR(20) DEFAULT 'APPROVED'
) COMMENT = 'Approved supplier-part combinations — 40,000 rows';

INSERT INTO SCS.INVENTORY.SUPPLIER_PART_APPROVAL
SELECT
    SEQ8() + 1 AS APPROVAL_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1 AS SUPPLIER_ID,
    MOD(ABS(HASH(SEQ8(), 20260918)), 1200) + 1 AS SITE_ID,
    MOD(ABS(HASH(SEQ8(), 20260919)), 30000) + 1 AS PART_ID,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260920)), 1000), '2023-01-01') AS APPROVAL_DATE,
    'APPROVED'
FROM TABLE(GENERATOR(ROWCOUNT => 40000));

-- =============================================================================
-- SECTION 5: TRANSACTIONAL DATA
-- =============================================================================

-- PO_HEADER (20,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.PO_HEADER (
    PO_ID         INT          NOT NULL PRIMARY KEY,
    PO_NUMBER     VARCHAR(20)  NOT NULL,
    SUPPLIER_ID   INT          NOT NULL,
    PLANT_ID      INT          NOT NULL,
    ORDER_DATE    DATE         NOT NULL,
    CURRENCY_CODE VARCHAR(3)   DEFAULT 'USD',
    STATUS        VARCHAR(20)  NOT NULL COMMENT 'OPEN, RECEIVED, PARTIAL, CANCELLED'
) COMMENT = 'Purchase order headers — 20,000 POs';

INSERT INTO SCS.INVENTORY.PO_HEADER
SELECT
    SEQ8() + 1 AS PO_ID,
    'PO-' || LPAD((SEQ8()+1)::VARCHAR, 7, '0') AS PO_NUMBER,
    MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1 AS SUPPLIER_ID,
    MOD(ABS(HASH(SEQ8(), 20260918)), 12) + 1 AS PLANT_ID,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260919)), 1370), '2023-01-01') AS ORDER_DATE,
    'USD',
    CASE MOD(ABS(HASH(SEQ8(), 20260920)), 10)
        WHEN 0 THEN 'OPEN'
        WHEN 1 THEN 'PARTIAL'
        WHEN 9 THEN 'CANCELLED'
        ELSE 'RECEIVED'
    END
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- PO_LINE (60,000 rows — 3 lines per PO avg)
CREATE OR REPLACE TABLE SCS.INVENTORY.PO_LINE (
    PO_LINE_ID   INT           NOT NULL PRIMARY KEY,
    PO_ID        INT           NOT NULL,
    PART_ID      INT           NOT NULL,
    QUANTITY     DECIMAL(12,2) NOT NULL,
    UNIT_PRICE   DECIMAL(10,2) NOT NULL,
    PROMISE_DATE DATE          NOT NULL COMMENT 'Original supplier promise date'
) COMMENT = 'Purchase order line items — 60,000 lines';

INSERT INTO SCS.INVENTORY.PO_LINE
SELECT
    SEQ8() + 1 AS PO_LINE_ID,
    DIV0(SEQ8(), 3) + 1 AS PO_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 30000) + 1 AS PART_ID,
    (10 + MOD(ABS(HASH(SEQ8(), 20260918)), 990))::DECIMAL(12,2) AS QUANTITY,
    ROUND(0.50 + MOD(ABS(HASH(SEQ8(), 20260919)), 50000) / 100.0, 2) AS UNIT_PRICE,
    DATEADD(DAY,
        MOD(ABS(HASH(SEQ8(), 20260920)), 1370) + 14 + MOD(ABS(HASH(SEQ8(), 20260921)), 45),
        '2023-01-01') AS PROMISE_DATE
FROM TABLE(GENERATOR(ROWCOUNT => 60000));

-- GOODS_RECEIPT (90,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.GOODS_RECEIPT (
    RECEIPT_ID     INT           NOT NULL PRIMARY KEY,
    PO_LINE_ID     INT           NOT NULL,
    RECEIPT_DATE   DATE          NOT NULL COMMENT 'Actual physical receipt date',
    QUANTITY_RECEIVED DECIMAL(12,2) NOT NULL,
    WAREHOUSE_ID   INT           NOT NULL,
    DAYS_VARIANCE  INT           NOT NULL COMMENT 'Days early (negative) or late (positive) vs promise date'
) COMMENT = 'Goods receipts — 90,000 receipts against PO lines';

INSERT INTO SCS.INVENTORY.GOODS_RECEIPT
SELECT
    SEQ8() + 1 AS RECEIPT_ID,
    MOD(SEQ8(), 60000) + 1 AS PO_LINE_ID,
    DATEADD(DAY,
        MOD(ABS(HASH(SEQ8(), 20260920)), 1370) + 14 + MOD(ABS(HASH(SEQ8(), 20260921)), 45)
        + (CASE
            -- Problem suppliers: 38% late, skew +3 to +20 days
            WHEN MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1 <= 3
                 AND MOD(ABS(HASH(SEQ8(), 20260922)), 100) < 38
            THEN 3 + MOD(ABS(HASH(SEQ8(), 20260923)), 18)
            -- Normal suppliers: ~14% late, -5 to +10
            WHEN MOD(ABS(HASH(SEQ8(), 20260924)), 100) < 14
            THEN 1 + MOD(ABS(HASH(SEQ8(), 20260925)), 10)
            ELSE -5 + MOD(ABS(HASH(SEQ8(), 20260926)), 6)
           END),
        '2023-01-01') AS RECEIPT_DATE,
    GREATEST(1, (10 + MOD(ABS(HASH(SEQ8(), 20260918)), 990))::DECIMAL(12,2)
        - CASE WHEN MOD(ABS(HASH(SEQ8(), 20260927)), 100) < 9 THEN MOD(ABS(HASH(SEQ8(), 20260928)), 200) ELSE 0 END
    ) AS QUANTITY_RECEIVED,
    MOD(ABS(HASH(SEQ8(), 20260929)), 25) + 1 AS WAREHOUSE_ID,
    CASE
        WHEN MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1 <= 3
             AND MOD(ABS(HASH(SEQ8(), 20260922)), 100) < 38
        THEN 3 + MOD(ABS(HASH(SEQ8(), 20260923)), 18)
        WHEN MOD(ABS(HASH(SEQ8(), 20260924)), 100) < 14
        THEN 1 + MOD(ABS(HASH(SEQ8(), 20260925)), 10)
        ELSE -5 + MOD(ABS(HASH(SEQ8(), 20260926)), 6)
    END AS DAYS_VARIANCE
FROM TABLE(GENERATOR(ROWCOUNT => 90000));

-- SALES_ORDER_HEADER (10,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.SALES_ORDER_HEADER (
    ORDER_ID      INT          NOT NULL PRIMARY KEY,
    ORDER_NUMBER  VARCHAR(20)  NOT NULL,
    CUSTOMER_ID   INT          NOT NULL,
    ORDER_DATE    DATE         NOT NULL,
    PLANT_ID      INT          NOT NULL,
    STATUS        VARCHAR(20)  NOT NULL
) COMMENT = 'Customer sales order headers — 10,000 orders';

INSERT INTO SCS.INVENTORY.SALES_ORDER_HEADER
SELECT
    SEQ8() + 1,
    'SO-' || LPAD((SEQ8()+1)::VARCHAR, 7, '0'),
    MOD(ABS(HASH(SEQ8(), 20260917)), 80) + 1,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260918)), 1370), '2023-01-01'),
    MOD(ABS(HASH(SEQ8(), 20260919)), 12) + 1,
    CASE MOD(ABS(HASH(SEQ8(), 20260920)), 5)
        WHEN 0 THEN 'OPEN'
        WHEN 1 THEN 'PARTIAL'
        ELSE 'SHIPPED'
    END
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- SALES_ORDER_LINE (40,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.SALES_ORDER_LINE (
    ORDER_LINE_ID  INT           NOT NULL PRIMARY KEY,
    ORDER_ID       INT           NOT NULL,
    PRODUCT_ID     INT           NOT NULL,
    QUANTITY       DECIMAL(12,2) NOT NULL,
    UNIT_PRICE     DECIMAL(10,2) NOT NULL,
    REQUESTED_DATE DATE          NOT NULL
) COMMENT = 'Sales order line items — 40,000 lines';

INSERT INTO SCS.INVENTORY.SALES_ORDER_LINE
SELECT
    SEQ8() + 1,
    MOD(SEQ8(), 10000) + 1,
    MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1,
    (5 + MOD(ABS(HASH(SEQ8(), 20260918)), 495))::DECIMAL(12,2),
    ROUND(50 + MOD(ABS(HASH(SEQ8(), 20260919)), 200000) / 100.0, 2),
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260920)), 1370) + 7 + MOD(ABS(HASH(SEQ8(), 20260921)), 30), '2023-01-01')
FROM TABLE(GENERATOR(ROWCOUNT => 40000));

-- SHIPMENT_HEADER (18,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.SHIPMENT_HEADER (
    SHIPMENT_ID   INT          NOT NULL PRIMARY KEY,
    CARRIER_ID    INT          NOT NULL,
    LANE_ID       INT          NOT NULL,
    SHIP_DATE     DATE         NOT NULL,
    DELIVERY_DATE DATE,
    STATUS        VARCHAR(20)  NOT NULL
) COMMENT = 'Shipment headers — 18,000 shipments';

INSERT INTO SCS.INVENTORY.SHIPMENT_HEADER
SELECT
    SEQ8() + 1,
    MOD(ABS(HASH(SEQ8(), 20260917)), 20) + 1,
    MOD(ABS(HASH(SEQ8(), 20260918)), 500) + 1,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260919)), 1370), '2023-01-01'),
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260919)), 1370) + 5 + MOD(ABS(HASH(SEQ8(), 20260920)), 35), '2023-01-01'),
    CASE MOD(ABS(HASH(SEQ8(), 20260921)), 10)
        WHEN 0 THEN 'IN_TRANSIT'
        WHEN 1 THEN 'DELAYED'
        ELSE 'DELIVERED'
    END
FROM TABLE(GENERATOR(ROWCOUNT => 18000));

-- SHIPMENT_LINE (60,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.SHIPMENT_LINE (
    SHIPMENT_LINE_ID INT           NOT NULL PRIMARY KEY,
    SHIPMENT_ID      INT           NOT NULL,
    ORDER_LINE_ID    INT,
    PO_LINE_ID       INT,
    QUANTITY         DECIMAL(12,2) NOT NULL
) COMMENT = 'Shipment line items linking to orders or POs';

INSERT INTO SCS.INVENTORY.SHIPMENT_LINE
SELECT
    SEQ8() + 1,
    MOD(SEQ8(), 18000) + 1,
    CASE WHEN MOD(SEQ8(), 2) = 0 THEN MOD(ABS(HASH(SEQ8(), 20260917)), 40000) + 1 ELSE NULL END,
    CASE WHEN MOD(SEQ8(), 2) = 1 THEN MOD(ABS(HASH(SEQ8(), 20260918)), 60000) + 1 ELSE NULL END,
    (5 + MOD(ABS(HASH(SEQ8(), 20260919)), 495))::DECIMAL(12,2)
FROM TABLE(GENERATOR(ROWCOUNT => 60000));

-- SHIPMENT_MILESTONE_EVENT (250,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.SHIPMENT_MILESTONE_EVENT (
    EVENT_ID      INT          NOT NULL PRIMARY KEY,
    SHIPMENT_ID   INT          NOT NULL,
    MILESTONE     VARCHAR(50)  NOT NULL,
    EVENT_TS      TIMESTAMP_NTZ NOT NULL,
    LOCATION      VARCHAR(100)
) COMMENT = 'Shipment tracking milestones — 250,000 events';

INSERT INTO SCS.INVENTORY.SHIPMENT_MILESTONE_EVENT
WITH MILESTONES AS (
    SELECT R.VALUE::VARCHAR AS MS, R.INDEX AS IDX FROM TABLE(FLATTEN(INPUT => ARRAY_CONSTRUCT(
        'BOOKING_CONFIRMED','PICKED_UP','GATE_IN','LOADED','DEPARTED',
        'IN_TRANSIT','TRANSSHIPMENT','ARRIVED_PORT','CUSTOMS_CLEARANCE',
        'GATE_OUT','OUT_FOR_DELIVERY','DELIVERED','POD_SIGNED'
    ))) R
)
SELECT
    SEQ8() + 1 AS EVENT_ID,
    DIV0(SEQ8(), 14) + 1 AS SHIPMENT_ID,
    M.MS AS MILESTONE,
    DATEADD(HOUR,
        MOD(ABS(HASH(SEQ8(), 20260919)), 1370) * 24 + M.IDX * 24 + MOD(ABS(HASH(SEQ8(), 20260920)), 24)
        -- 2% non-monotonic timestamps
        + CASE WHEN MOD(ABS(HASH(SEQ8(), 20260930)), 100) < 2 THEN -48 ELSE 0 END,
        '2023-01-01'::TIMESTAMP_NTZ) AS EVENT_TS,
    ARRAY_CONSTRUCT('Shanghai','Shenzhen','Singapore','Busan','Los Angeles',
        'Long Beach','Guadalajara','Houston','Hamburg','Rotterdam',
        'Tokyo','Penang','Mumbai','Savannah')[MOD(ABS(HASH(SEQ8(), 20260921)), 14)]::VARCHAR AS LOCATION
FROM TABLE(GENERATOR(ROWCOUNT => 250000)) G
LEFT JOIN MILESTONES M ON M.IDX = MOD(SEQ8(), 14)
WHERE DIV0(SEQ8(), 14) + 1 <= 18000;

-- IOT_SENSOR_READING (500,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.IOT_SENSOR_READING (
    READING_ID    INT           NOT NULL PRIMARY KEY,
    SHIPMENT_ID   INT           NOT NULL,
    READING_TS    TIMESTAMP_NTZ NOT NULL,
    TEMPERATURE_C DECIMAL(5,1),
    HUMIDITY_PCT  DECIMAL(5,1),
    SHOCK_G       DECIMAL(5,2),
    TILT_DEG      DECIMAL(5,1),
    GPS_LAT       DECIMAL(9,6),
    GPS_LON       DECIMAL(9,6),
    BREACH_FLAG   BOOLEAN       NOT NULL COMMENT 'TRUE if any reading exceeds threshold'
) COMMENT = 'IoT container sensor readings — 500,000 rows, ~1.5% breach rate';

INSERT INTO SCS.INVENTORY.IOT_SENSOR_READING
SELECT
    SEQ8() + 1 AS READING_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 18000) + 1 AS SHIPMENT_ID,
    DATEADD(MINUTE,
        MOD(ABS(HASH(SEQ8(), 20260918)), 1970000),
        '2023-01-01'::TIMESTAMP_NTZ) AS READING_TS,
    ROUND(18.0 + MOD(ABS(HASH(SEQ8(), 20260919)), 200) / 10.0
        + CASE WHEN MOD(ABS(HASH(SEQ8(), 20260930)), 100) < 2 THEN 25 ELSE 0 END, 1) AS TEMPERATURE_C,
    ROUND(30.0 + MOD(ABS(HASH(SEQ8(), 20260920)), 500) / 10.0, 1) AS HUMIDITY_PCT,
    ROUND(MOD(ABS(HASH(SEQ8(), 20260921)), 50) / 100.0
        + CASE WHEN MOD(ABS(HASH(SEQ8(), 20260931)), 100) < 2 THEN 3.5 ELSE 0 END, 2) AS SHOCK_G,
    ROUND(MOD(ABS(HASH(SEQ8(), 20260922)), 100) / 10.0, 1) AS TILT_DEG,
    ROUND(10.0 + MOD(ABS(HASH(SEQ8(), 20260923)), 600) / 10.0, 6) AS GPS_LAT,
    ROUND(80.0 + MOD(ABS(HASH(SEQ8(), 20260924)), 2000) / 10.0, 6) AS GPS_LON,
    (MOD(ABS(HASH(SEQ8(), 20260930)), 100) < 2  -- temp breach
     OR MOD(ABS(HASH(SEQ8(), 20260931)), 100) < 2  -- shock breach
     OR ROUND(30.0 + MOD(ABS(HASH(SEQ8(), 20260920)), 500) / 10.0, 1) > 75  -- humidity breach
    ) AS BREACH_FLAG
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- WORK_ORDER (10,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.WORK_ORDER (
    WORK_ORDER_ID INT         NOT NULL PRIMARY KEY,
    PRODUCT_ID    INT         NOT NULL,
    PLANT_ID      INT         NOT NULL,
    START_DATE    DATE        NOT NULL,
    END_DATE      DATE,
    QUANTITY      DECIMAL(12,2) NOT NULL,
    STATUS        VARCHAR(20) NOT NULL
) COMMENT = 'Manufacturing work orders — 10,000';

INSERT INTO SCS.INVENTORY.WORK_ORDER
SELECT
    SEQ8() + 1,
    MOD(ABS(HASH(SEQ8(), 20260917)), 500) + 1,
    MOD(ABS(HASH(SEQ8(), 20260918)), 12) + 1,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260919)), 1370), '2023-01-01'),
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260919)), 1370) + 3 + MOD(ABS(HASH(SEQ8(), 20260920)), 14), '2023-01-01'),
    (50 + MOD(ABS(HASH(SEQ8(), 20260921)), 950))::DECIMAL(12,2),
    CASE MOD(ABS(HASH(SEQ8(), 20260922)), 5)
        WHEN 0 THEN 'IN_PROGRESS'
        WHEN 1 THEN 'ON_HOLD'
        ELSE 'COMPLETED'
    END
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- QUALITY_INSPECTION (10,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.QUALITY_INSPECTION (
    INSPECTION_ID   INT          NOT NULL PRIMARY KEY,
    RECEIPT_ID      INT          NOT NULL,
    PART_ID         INT          NOT NULL,
    SUPPLIER_ID     INT          NOT NULL,
    INSPECTION_DATE DATE         NOT NULL,
    SAMPLE_SIZE     INT          NOT NULL,
    DEFECT_COUNT    INT          NOT NULL,
    RESULT          VARCHAR(20)  NOT NULL COMMENT 'PASS, FAIL, CONDITIONAL',
    PPM             DECIMAL(10,1) NOT NULL COMMENT 'Parts per million defect rate'
) COMMENT = 'Incoming quality inspections — 10,000';

INSERT INTO SCS.INVENTORY.QUALITY_INSPECTION
SELECT
    SEQ8() + 1 AS INSPECTION_ID,
    MOD(ABS(HASH(SEQ8(), 20260917)), 90000) + 1 AS RECEIPT_ID,
    MOD(ABS(HASH(SEQ8(), 20260918)), 30000) + 1 AS PART_ID,
    MOD(ABS(HASH(SEQ8(), 20260919)), 500) + 1 AS SUPPLIER_ID,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260920)), 1370), '2023-01-01') AS INSPECTION_DATE,
    100 + MOD(ABS(HASH(SEQ8(), 20260921)), 900) AS SAMPLE_SIZE,
    CASE
        WHEN MOD(ABS(HASH(SEQ8(), 20260919)), 500) + 1 <= 3 THEN MOD(ABS(HASH(SEQ8(), 20260922)), 15)
        ELSE MOD(ABS(HASH(SEQ8(), 20260922)), 5)
    END AS DEFECT_COUNT,
    CASE
        WHEN MOD(ABS(HASH(SEQ8(), 20260919)), 500) + 1 <= 3 AND MOD(ABS(HASH(SEQ8(), 20260922)), 15) > 5 THEN 'FAIL'
        WHEN MOD(ABS(HASH(SEQ8(), 20260922)), 5) > 3 THEN 'CONDITIONAL'
        ELSE 'PASS'
    END AS RESULT,
    ROUND(CASE
        WHEN MOD(ABS(HASH(SEQ8(), 20260919)), 500) + 1 <= 3
        THEN MOD(ABS(HASH(SEQ8(), 20260922)), 15) * 1000000.0 / (100 + MOD(ABS(HASH(SEQ8(), 20260921)), 900))
        ELSE MOD(ABS(HASH(SEQ8(), 20260922)), 5) * 1000000.0 / (100 + MOD(ABS(HASH(SEQ8(), 20260921)), 900))
    END, 1) AS PPM
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- NONCONFORMANCE_REPORT (1,000 rows)
CREATE OR REPLACE TABLE SCS.INVENTORY.NONCONFORMANCE_REPORT (
    NCR_ID        INT          NOT NULL PRIMARY KEY,
    INSPECTION_ID INT,
    SUPPLIER_ID   INT          NOT NULL,
    PART_ID       INT          NOT NULL,
    PLANT_ID      INT          NOT NULL,
    NCR_DATE      DATE         NOT NULL,
    SEVERITY      VARCHAR(20)  NOT NULL COMMENT 'CRITICAL, MAJOR, MINOR',
    ROOT_CAUSE    VARCHAR(500),
    DISPOSITION   VARCHAR(20)  NOT NULL COMMENT 'SCRAP, REWORK, USE_AS_IS, RETURN',
    STATUS        VARCHAR(20)  DEFAULT 'CLOSED'
) COMMENT = 'Non-conformance reports — 1,000 NCRs';

INSERT INTO SCS.INVENTORY.NONCONFORMANCE_REPORT
SELECT
    SEQ8() + 1,
    MOD(ABS(HASH(SEQ8(), 20260917)), 10000) + 1,
    -- Bias toward problem suppliers
    CASE WHEN MOD(ABS(HASH(SEQ8(), 20260930)), 100) < 30
        THEN MOD(ABS(HASH(SEQ8(), 20260918)), 3) + 1
        ELSE MOD(ABS(HASH(SEQ8(), 20260919)), 500) + 1
    END,
    MOD(ABS(HASH(SEQ8(), 20260920)), 30000) + 1,
    MOD(ABS(HASH(SEQ8(), 20260921)), 12) + 1,
    DATEADD(DAY, MOD(ABS(HASH(SEQ8(), 20260922)), 1370), '2023-01-01'),
    ARRAY_CONSTRUCT('CRITICAL','MAJOR','MINOR')[MOD(ABS(HASH(SEQ8(), 20260923)), 3)]::VARCHAR,
    ARRAY_CONSTRUCT(
        'Material contamination detected during incoming inspection',
        'Dimensional out-of-spec on critical feature',
        'Solder joint defect from supplier manufacturing process',
        'ESD damage during shipping — insufficient packaging',
        'Wrong revision shipped by supplier',
        'Documentation mismatch between ASN and physical receipt',
        'Surface finish degradation due to humidity exposure in transit',
        'Cracked ceramic substrate from excessive shock during transport',
        'Mixed lot with unapproved sub-component substitution',
        'Electrical test failure — parametric drift beyond tolerance'
    )[MOD(ABS(HASH(SEQ8(), 20260924)), 10)]::VARCHAR,
    ARRAY_CONSTRUCT('SCRAP','REWORK','USE_AS_IS','RETURN')[MOD(ABS(HASH(SEQ8(), 20260925)), 4)]::VARCHAR,
    CASE WHEN MOD(ABS(HASH(SEQ8(), 20260926)), 10) = 0 THEN 'OPEN' ELSE 'CLOSED' END
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- =============================================================================
-- SECTION 6: INVENTORY SNAPSHOT (simplified — daily part x warehouse)
-- We'll generate ~1.2M rows as part x warehouse x monthly snapshots
-- =============================================================================

CREATE OR REPLACE TABLE SCS.INVENTORY.FACT_INVENTORY_SNAPSHOT (
    SNAPSHOT_ID     INT           NOT NULL PRIMARY KEY,
    SNAPSHOT_DATE   DATE          NOT NULL,
    PART_ID         INT           NOT NULL,
    WAREHOUSE_ID    INT           NOT NULL,
    ON_HAND_QTY     DECIMAL(12,2) NOT NULL,
    UNIT_COST_USD   DECIMAL(10,2) NOT NULL,
    ON_HAND_VALUE   DECIMAL(14,2) NOT NULL COMMENT 'on_hand_qty * unit_cost_usd',
    DAILY_USAGE_QTY DECIMAL(10,2) COMMENT 'Average daily consumption',
    DOI             DECIMAL(10,1) COMMENT 'Days of inventory = on_hand / daily_usage'
) COMMENT = 'Inventory snapshots — ~1.2M rows (part x warehouse x month-end)';

INSERT INTO SCS.INVENTORY.FACT_INVENTORY_SNAPSHOT
SELECT
    SEQ8() + 1 AS SNAPSHOT_ID,
    DATEADD(MONTH, MOD(SEQ8(), 48), '2023-01-31')::DATE AS SNAPSHOT_DATE,
    MOD(ABS(HASH(SEQ8(), 20260917)), 1000) + 1 AS PART_ID,
    MOD(ABS(HASH(SEQ8(), 20260918)), 25) + 1 AS WAREHOUSE_ID,
    GREATEST(0, (100 + MOD(ABS(HASH(SEQ8(), 20260919)), 9900))::DECIMAL(12,2)) AS ON_HAND_QTY,
    ROUND(0.50 + MOD(ABS(HASH(SEQ8(), 20260920)), 50000) / 100.0, 2) AS UNIT_COST_USD,
    ROUND(GREATEST(0, (100 + MOD(ABS(HASH(SEQ8(), 20260919)), 9900)))
        * (0.50 + MOD(ABS(HASH(SEQ8(), 20260920)), 50000) / 100.0), 2) AS ON_HAND_VALUE,
    GREATEST(0.1, ROUND(MOD(ABS(HASH(SEQ8(), 20260921)), 500) / 10.0, 2)) AS DAILY_USAGE_QTY,
    ROUND(
        GREATEST(0, (100 + MOD(ABS(HASH(SEQ8(), 20260919)), 9900)))
        / NULLIF(GREATEST(0.1, MOD(ABS(HASH(SEQ8(), 20260921)), 500) / 10.0), 0),
    1) AS DOI
FROM TABLE(GENERATOR(ROWCOUNT => 1200000));

-- =============================================================================
-- VALIDATION
-- =============================================================================
SELECT 'DIM_DATE' AS TBL, COUNT(*) AS ROW_COUNT FROM SCS.INVENTORY.DIM_DATE
UNION ALL SELECT 'DIM_GEO_REGION', COUNT(*) FROM SCS.INVENTORY.DIM_GEO_REGION
UNION ALL SELECT 'DIM_GEO_COUNTRY', COUNT(*) FROM SCS.INVENTORY.DIM_GEO_COUNTRY
UNION ALL SELECT 'DIM_COMMODITY', COUNT(*) FROM SCS.INVENTORY.DIM_COMMODITY
UNION ALL SELECT 'DIM_SUB_COMMODITY', COUNT(*) FROM SCS.INVENTORY.DIM_SUB_COMMODITY
UNION ALL SELECT 'DIM_CURRENCY', COUNT(*) FROM SCS.INVENTORY.DIM_CURRENCY
UNION ALL SELECT 'DIM_UOM', COUNT(*) FROM SCS.INVENTORY.DIM_UOM
UNION ALL SELECT 'DIM_INCOTERM', COUNT(*) FROM SCS.INVENTORY.DIM_INCOTERM
UNION ALL SELECT 'DIM_PORT', COUNT(*) FROM SCS.INVENTORY.DIM_PORT
UNION ALL SELECT 'DIM_SUPPLIER', COUNT(*) FROM SCS.INVENTORY.DIM_SUPPLIER
UNION ALL SELECT 'DIM_SUPPLIER_SITE', COUNT(*) FROM SCS.INVENTORY.DIM_SUPPLIER_SITE
UNION ALL SELECT 'DIM_MANUFACTURER', COUNT(*) FROM SCS.INVENTORY.DIM_MANUFACTURER
UNION ALL SELECT 'DIM_PART', COUNT(*) FROM SCS.INVENTORY.DIM_PART
UNION ALL SELECT 'DIM_PRODUCT_FAMILY', COUNT(*) FROM SCS.INVENTORY.DIM_PRODUCT_FAMILY
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM SCS.INVENTORY.DIM_PRODUCT
UNION ALL SELECT 'BOM_HEADER', COUNT(*) FROM SCS.INVENTORY.BOM_HEADER
UNION ALL SELECT 'BOM_LINE', COUNT(*) FROM SCS.INVENTORY.BOM_LINE
UNION ALL SELECT 'DIM_PLANT', COUNT(*) FROM SCS.INVENTORY.DIM_PLANT
UNION ALL SELECT 'DIM_WAREHOUSE', COUNT(*) FROM SCS.INVENTORY.DIM_WAREHOUSE
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*) FROM SCS.INVENTORY.DIM_CUSTOMER
UNION ALL SELECT 'DIM_CARRIER', COUNT(*) FROM SCS.INVENTORY.DIM_CARRIER
UNION ALL SELECT 'DIM_LANE', COUNT(*) FROM SCS.INVENTORY.DIM_LANE
UNION ALL SELECT 'DIM_CONTRACT', COUNT(*) FROM SCS.INVENTORY.DIM_CONTRACT
UNION ALL SELECT 'SUPPLIER_PART_APPROVAL', COUNT(*) FROM SCS.INVENTORY.SUPPLIER_PART_APPROVAL
UNION ALL SELECT 'PO_HEADER', COUNT(*) FROM SCS.INVENTORY.PO_HEADER
UNION ALL SELECT 'PO_LINE', COUNT(*) FROM SCS.INVENTORY.PO_LINE
UNION ALL SELECT 'GOODS_RECEIPT', COUNT(*) FROM SCS.INVENTORY.GOODS_RECEIPT
UNION ALL SELECT 'SALES_ORDER_HEADER', COUNT(*) FROM SCS.INVENTORY.SALES_ORDER_HEADER
UNION ALL SELECT 'SALES_ORDER_LINE', COUNT(*) FROM SCS.INVENTORY.SALES_ORDER_LINE
UNION ALL SELECT 'SHIPMENT_HEADER', COUNT(*) FROM SCS.INVENTORY.SHIPMENT_HEADER
UNION ALL SELECT 'SHIPMENT_LINE', COUNT(*) FROM SCS.INVENTORY.SHIPMENT_LINE
UNION ALL SELECT 'SHIPMENT_MILESTONE', COUNT(*) FROM SCS.INVENTORY.SHIPMENT_MILESTONE_EVENT
UNION ALL SELECT 'IOT_SENSOR_READING', COUNT(*) FROM SCS.INVENTORY.IOT_SENSOR_READING
UNION ALL SELECT 'WORK_ORDER', COUNT(*) FROM SCS.INVENTORY.WORK_ORDER
UNION ALL SELECT 'QUALITY_INSPECTION', COUNT(*) FROM SCS.INVENTORY.QUALITY_INSPECTION
UNION ALL SELECT 'NCR', COUNT(*) FROM SCS.INVENTORY.NONCONFORMANCE_REPORT
UNION ALL SELECT 'INVENTORY_SNAPSHOT', COUNT(*) FROM SCS.INVENTORY.FACT_INVENTORY_SNAPSHOT
ORDER BY TBL;
